/*
 * Superposition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-05
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicableVariantsResponseContent {
    #[serde(rename = "applicable_variants")]
    pub applicable_variants: Vec<models::Variant>,
}

impl ApplicableVariantsResponseContent {
    pub fn new(applicable_variants: Vec<models::Variant>) -> ApplicableVariantsResponseContent {
        ApplicableVariantsResponseContent {
            applicable_variants,
        }
    }
}

