/*
 * Superposition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-05
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContextPutOut {
    #[serde(rename = "context_id", skip_serializing_if = "Option::is_none")]
    pub context_id: Option<String>,
    #[serde(rename = "override_id", skip_serializing_if = "Option::is_none")]
    pub override_id: Option<String>,
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<f64>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "change_reason", skip_serializing_if = "Option::is_none")]
    pub change_reason: Option<String>,
}

impl ContextPutOut {
    pub fn new() -> ContextPutOut {
        ContextPutOut {
            context_id: None,
            override_id: None,
            weight: None,
            description: None,
            change_reason: None,
        }
    }
}

