/*
 * Superposition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-05
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContextMove {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "condition")]
    pub condition: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "change_reason")]
    pub change_reason: String,
}

impl ContextMove {
    pub fn new(condition: std::collections::HashMap<String, serde_json::Value>, change_reason: String) -> ContextMove {
        ContextMove {
            id: None,
            condition,
            description: None,
            change_reason,
        }
    }
}

