/*
 * Superposition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-05
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ContextAction {
    Put(Box<models::Put>),
    Replace(Box<models::Replace>),
    Delete(Box<models::Delete>),
    Move(Box<models::Move>),
}

impl Default for ContextAction {
    fn default() -> Self {
        Self::Put(Default::default())
    }
}

