/*
 * Superposition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-05
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ContextActionOut {
    Put1(Box<models::Put1>),
    Replace1(Box<models::Replace1>),
    Delete(Box<models::Delete>),
    Move1(Box<models::Move1>),
}

impl Default for ContextActionOut {
    fn default() -> Self {
        Self::Put1(Default::default())
    }
}

