/*
 * Superposition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-05
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContextPartial {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
    pub condition: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<f64>,
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<f64>,
    #[serde(rename = "override_with_keys", skip_serializing_if = "Option::is_none")]
    pub override_with_keys: Option<Vec<String>>,
}

impl ContextPartial {
    pub fn new() -> ContextPartial {
        ContextPartial {
            id: None,
            condition: None,
            priority: None,
            weight: None,
            override_with_keys: None,
        }
    }
}

