/*
 * Superposition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-05
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetConfigResponseContent {
    #[serde(rename = "contexts", skip_serializing_if = "Option::is_none")]
    pub contexts: Option<Vec<models::ContextPartial>>,
    #[serde(rename = "overrides", skip_serializing_if = "Option::is_none")]
    pub overrides: Option<std::collections::HashMap<String, std::collections::HashMap<String, serde_json::Value>>>,
    #[serde(rename = "default_configs", skip_serializing_if = "Option::is_none")]
    pub default_configs: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl GetConfigResponseContent {
    pub fn new() -> GetConfigResponseContent {
        GetConfigResponseContent {
            contexts: None,
            overrides: None,
            default_configs: None,
        }
    }
}

