/*
 * Superposition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-05
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Move1 {
    #[serde(rename = "MOVE")]
    pub r#move: Box<models::ContextMoveOut>,
}

impl Move1 {
    pub fn new(r#move: models::ContextMoveOut) -> Move1 {
        Move1 {
            r#move: Box::new(r#move),
        }
    }
}

