/*
 * Superposition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-05
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Put {
    #[serde(rename = "PUT")]
    pub put: Box<models::ContextPut>,
}

impl Put {
    pub fn new(put: models::ContextPut) -> Put {
        Put {
            put: Box::new(put),
        }
    }
}

