/*
 * Superposition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-05
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Replace {
    #[serde(rename = "REPLACE")]
    pub replace: Box<models::ContextPut>,
}

impl Replace {
    pub fn new(replace: models::ContextPut) -> Replace {
        Replace {
            replace: Box::new(replace),
        }
    }
}

