/*
 * Superposition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-05
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TestResponseContent {
    #[serde(rename = "message")]
    pub message: String,
}

impl TestResponseContent {
    pub fn new(message: String) -> TestResponseContent {
        TestResponseContent {
            message,
        }
    }
}

