/*
 * Superposition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-05
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VariantType {
    #[serde(rename = "CONTROL")]
    Control,
    #[serde(rename = "EXPERIMENTAL")]
    Experimental,

}

impl std::fmt::Display for VariantType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Control => write!(f, "CONTROL"),
            Self::Experimental => write!(f, "EXPERIMENTAL"),
        }
    }
}

impl Default for VariantType {
    fn default() -> VariantType {
        Self::Control
    }
}

