/*
 * Superposition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-05
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VariantUpdateRequest {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "overrides", deserialize_with = "Option::deserialize")]
    pub overrides: Option<serde_json::Value>,
}

impl VariantUpdateRequest {
    pub fn new(id: String, overrides: Option<serde_json::Value>) -> VariantUpdateRequest {
        VariantUpdateRequest {
            id,
            overrides,
        }
    }
}

